## Loconotion Site Configuration File ##
# full .toml configuration example file to showcase all of Loconotion's available settings
# check out https://github.com/toml-lang/toml for more info on the toml format

# name of the folder that the site will be generated in
name = "tolerant"

# the notion.so page to being parsing from. This page will become the index.html
# of the generated site, and loconotion will parse all sub-pages present on the page
#page = "https://infohu.notion.site/Tolerant-eacfda26cfc040febb37c5e7f45c2574"
page = "https://deadpan-earwig-585.notion.site/Tolerant-e12e9f1c4e534e20b1dd6fee32ed334f"


# optionally apply notion's dark mode, remove the line below to use the default light mode
#theme = "dark"

## Global Site Settings ##
# this [site] table defines override settings for the whole site
# later on we will see how to define settings for a single page
[site]
  ## Custom Meta Tags ##
  [[site.meta]]
  name = "Tolerant"
  content = "Loconotion Test Site"
  [[site.meta]]
  name = "description"
  content = "blog"

  ## Custom Fonts ##
  [site.fonts]
  site = 'Ubuntu Mono'
  navbar = ''
  title = 'Montserrat'
  h1 = 'Montserrat'
  h2 = 'Montserrat'
  h3 = 'Montserrat'
  body = ''
  code = ''

  ## Custom Element Injection ##
  [[site.inject.head.link]]
  rel="icon" 
  sizes="16x16"
  type="image/png"
  href="/example/favicon-16x16.png"
  
  # the following injects this tag in the in the <body>:
  #   <script src="custom-script.js" type="text/javascript"></script>
  # note that all href / src files are copied to the root of the site folder 
  # regardless of their original path
  [[site.inject.body.script]]
  type="text/javascript"
  src="/example/custom-script.js"


[pages]
  # the following settings will only apply to this page: 
  #   https://www.notion.so/d2fa06f244e64f66880bb0491f58223d
  [pages.Programming-language-d43c139ba189475aa59a934a855461df]
    ## custom slugs ##
    # inside page settings, you can change the url for that page with the 'slug' key
    # e.g. page "/d2fa06f244e64f66880bb0491f58223d" will now map to "/games-list"
    slug = "gam"




